### ISSUE TITLE
:반짝임: feat: ErrorCode 기능 추가

### ISSUE THREAD

**Issue by MyohanMyolang** [BackofficeA4/main#12]
추가될 기능에 대해 설명해주세요
-프론트엔드에서 호출 실패를 받을 때 ErrorCode를 따로 정의하여 프론트엔드 쪽에서 에러 대응이 용이하게 하기 위해 ErrorCode를 정의하면 좋을 것 같습니다.

해야할 일들을 작성해주세요
- [x] Error Code를 어떻게 정의 할 것인가에 대한 논의
- [x] #13

**Comment by Re-eun** [comment]
-  Error Code 를 어떻게 정의 할 것인가에 대한 논의 

error code를 정의한 사례들을 찾아봤고 그 중 일부를 가져와봤습니다. 참고하면 좋을 것 같습니다.

1.  [RFC 7808 다섯 가지의 오류 메시지 스키마 ](https://www.baeldung.com/rest-api-error-handling-best-practices)

> {
    "type": "/errors/incorrect-user-pass",
    "title": "Incorrect username or password.",
    "status": 401,
    "detail": "Authentication failed due to incorrect username or password.",
    "instance": "/login/log/abc123"
}

이 중 type 으로 오류를 분류하고 title, detail 을 통해 전달할 메시지와 상세 내용만 정해도 괜찮을 것 같습니다.

2.  [카카오 REST API ](https://developers.kakao.com/docs/latest/ko/rest-api/reference)

> HTTP/1.1 400 Bad Request  
{
  "code":-10,
  "msg":"API limit has been exceeded."
}



카카오의 경우 http 상태 코드, type 과 별도로 error code 를 음수로 정의해서 표현하고 있습니다.
